module VerifyTop (
  input         clock,
  input         reset,
  input         io_imem_mem_req_ready,
  input         io_imem_mem_resp_valid,
  input  [3:0]  io_imem_mem_resp_bits_cmd,
  input  [63:0] io_imem_mem_resp_bits_rdata,
  input         io_imem_coh_req_valid,
  input  [31:0] io_imem_coh_req_bits_addr,
  input  [2:0]  io_imem_coh_req_bits_size,
  input  [3:0]  io_imem_coh_req_bits_cmd,
  input  [3:0]  io_imem_coh_req_bits_wmask,
  input  [31:0] io_imem_coh_req_bits_wdata,
  input         io_imem_coh_resp_ready,
  input         io_dmem_mem_req_ready,
  input         io_dmem_mem_resp_valid,
  input  [3:0]  io_dmem_mem_resp_bits_cmd,
  input  [63:0] io_dmem_mem_resp_bits_rdata,
  input         io_dmem_coh_req_valid,
  input  [31:0] io_dmem_coh_req_bits_addr,
  input  [2:0]  io_dmem_coh_req_bits_size,
  input  [3:0]  io_dmem_coh_req_bits_cmd,
  input  [3:0]  io_dmem_coh_req_bits_wmask,
  input  [31:0] io_dmem_coh_req_bits_wdata,
  input         io_dmem_coh_resp_ready,
  input         io_mmio_req_ready,
  input         io_mmio_resp_valid,
  input  [3:0]  io_mmio_resp_bits_cmd,
  input  [63:0] io_mmio_resp_bits_rdata,
  input         io_frontend_req_valid,
  input  [31:0] io_frontend_req_bits_addr,
  input  [2:0]  io_frontend_req_bits_size,
  input  [3:0]  io_frontend_req_bits_cmd,
  input  [3:0]  io_frontend_req_bits_wmask,
  input  [31:0] io_frontend_req_bits_wdata,
  input         io_frontend_resp_ready,
  output        io_dmem_coh_req_ready,
  output        io_imem_mem_req_valid,
  output [31:0] io_imem_mem_req_bits_addr,
  output [2:0]  io_imem_mem_req_bits_size,
  output [3:0]  io_imem_mem_req_bits_cmd,
  output [3:0]  io_imem_mem_req_bits_wmask,
  output [31:0] io_imem_mem_req_bits_wdata,
  output        io_imem_mem_resp_ready,
  output        io_imem_coh_req_ready,
  output        io_imem_coh_resp_valid,
  output [3:0]  io_imem_coh_resp_bits_cmd,
  output [63:0] io_imem_coh_resp_bits_rdata,
  output        io_dmem_mem_req_valid,
  output [31:0] io_dmem_mem_req_bits_addr,
  output [2:0]  io_dmem_mem_req_bits_size,
  output [3:0]  io_dmem_mem_req_bits_cmd,
  output [3:0]  io_dmem_mem_req_bits_wmask,
  output [31:0] io_dmem_mem_req_bits_wdata,
  output        io_dmem_mem_resp_ready,
  output        io_dmem_coh_resp_valid,
  output [3:0]  io_dmem_coh_resp_bits_cmd,
  output [63:0] io_dmem_coh_resp_bits_rdata,
  output        io_mmio_req_valid,
  output [31:0] io_mmio_req_bits_addr,
  output [2:0]  io_mmio_req_bits_size,
  output [3:0]  io_mmio_req_bits_cmd,
  output [3:0]  io_mmio_req_bits_wmask,
  output [31:0] io_mmio_req_bits_wdata,
  output        io_mmio_resp_ready,
  output        io_frontend_req_ready,
  output        io_frontend_resp_valid,
  output [3:0]  io_frontend_resp_bits_cmd,
  output [63:0] io_frontend_resp_bits_rdata,
  output        rvfi_valid, 
  output [63:0] rvfi_order, 
  output [31:0] rvfi_insn, 
  output        rvfi_trap, 
  output        rvfi_halt, 
  output        rvfi_intr, 
  output [1:0]  rvfi_mode, 
  output [1:0]  rvfi_ixl, 
  output [4:0]  rvfi_rs1_addr, 
  output [4:0]  rvfi_rs2_addr, 
  output [31:0] rvfi_rs1_rdata, 
  output [31:0] rvfi_rs2_rdata, 
  output [4:0]  rvfi_rd_addr, 
  output [31:0] rvfi_rd_wdata, 
  output [31:0] rvfi_pc_rdata, 
  output [31:0] rvfi_pc_wdata, 
  output [31:0] rvfi_mem_addr, 
  output [3:0]  rvfi_mem_rmask, 
  output [3:0]  rvfi_mem_wmask, 
  output [31:0] rvfi_mem_rdata, 
  output [31:0] rvfi_mem_wdata 
);

    reg  core_reset = 1'b1;

    always @(posedge clock) begin
        core_reset <= 1'b0; 
    end

    NutCore uut(
        .clock(clock),
        .reset(core_reset),
        .io_imem_mem_req_ready(io_imem_mem_req_ready),
        .io_imem_mem_resp_valid(io_imem_mem_resp_valid),
        .io_imem_mem_resp_bits_cmd(io_imem_mem_resp_bits_cmd),
        .io_imem_mem_resp_bits_rdata(io_imem_mem_resp_bits_rdata),
        .io_imem_coh_req_valid(io_imem_coh_req_valid),
        .io_imem_coh_req_bits_addr(io_imem_coh_req_bits_addr),
        .io_imem_coh_req_bits_size(io_imem_coh_req_bits_size),
        .io_imem_coh_req_bits_cmd(io_imem_coh_req_bits_cmd),
        .io_imem_coh_req_bits_wmask(io_imem_coh_req_bits_wmask),
        .io_imem_coh_req_bits_wdata(io_imem_coh_req_bits_wdata),
        .io_imem_coh_resp_ready(io_imem_coh_resp_ready),
        .io_dmem_mem_req_ready(io_dmem_mem_req_ready),
        .io_dmem_mem_resp_valid(io_dmem_mem_resp_valid),
        .io_dmem_mem_resp_bits_cmd(io_dmem_mem_resp_bits_cmd),
        .io_dmem_mem_resp_bits_rdata(io_dmem_mem_resp_bits_rdata),
        .io_dmem_coh_req_valid(io_dmem_coh_req_valid),
        .io_dmem_coh_req_bits_addr(io_dmem_coh_req_bits_addr),
        .io_dmem_coh_req_bits_size(io_dmem_coh_req_bits_size),
        .io_dmem_coh_req_bits_cmd(io_dmem_coh_req_bits_cmd),
        .io_dmem_coh_req_bits_wmask(io_dmem_coh_req_bits_wmask),
        .io_dmem_coh_req_bits_wdata(io_dmem_coh_req_bits_wdata),
        .io_dmem_coh_resp_ready(io_dmem_coh_resp_ready),
        .io_mmio_req_ready(io_mmio_req_ready),
        .io_mmio_resp_valid(io_mmio_resp_valid),
        .io_mmio_resp_bits_cmd(io_mmio_resp_bits_cmd),
        .io_mmio_resp_bits_rdata(io_mmio_resp_bits_rdata),
        .io_frontend_req_valid(io_frontend_req_valid),
        .io_frontend_req_bits_addr(io_frontend_req_bits_addr),
        .io_frontend_req_bits_size(io_frontend_req_bits_size),
        .io_frontend_req_bits_cmd(io_frontend_req_bits_cmd),
        .io_frontend_req_bits_wmask(io_frontend_req_bits_wmask),
        .io_frontend_req_bits_wdata(io_frontend_req_bits_wdata),
        .io_frontend_resp_ready(io_frontend_resp_ready),
        .io_dmem_coh_req_ready(io_dmem_coh_req_ready),
        .io_imem_mem_req_valid(io_imem_mem_req_valid),
        .io_imem_mem_req_bits_addr(io_imem_mem_req_bits_addr),
        .io_imem_mem_req_bits_size(io_imem_mem_req_bits_size),
        .io_imem_mem_req_bits_cmd(io_imem_mem_req_bits_cmd),
        .io_imem_mem_req_bits_wmask(io_imem_mem_req_bits_wmask),
        .io_imem_mem_req_bits_wdata(io_imem_mem_req_bits_wdata),
        .io_imem_mem_resp_ready(io_imem_mem_resp_ready),
        .io_imem_coh_req_ready(io_imem_coh_req_ready),
        .io_imem_coh_resp_valid(io_imem_coh_resp_valid),
        .io_imem_coh_resp_bits_cmd(io_imem_coh_resp_bits_cmd),
        .io_imem_coh_resp_bits_rdata(io_imem_coh_resp_bits_rdata),
        .io_dmem_mem_req_valid(io_dmem_mem_req_valid),
        .io_dmem_mem_req_bits_addr(io_dmem_mem_req_bits_addr),
        .io_dmem_mem_req_bits_size(io_dmem_mem_req_bits_size),
        .io_dmem_mem_req_bits_cmd(io_dmem_mem_req_bits_cmd),
        .io_dmem_mem_req_bits_wmask(io_dmem_mem_req_bits_wmask),
        .io_dmem_mem_req_bits_wdata(io_dmem_mem_req_bits_wdata),
        .io_dmem_mem_resp_ready(io_dmem_mem_resp_ready),
        .io_dmem_coh_resp_valid(io_dmem_coh_resp_valid),
        .io_dmem_coh_resp_bits_cmd(io_dmem_coh_resp_bits_cmd),
        .io_dmem_coh_resp_bits_rdata(io_dmem_coh_resp_bits_rdata),
        .io_mmio_req_valid(io_mmio_req_valid),
        .io_mmio_req_bits_addr(io_mmio_req_bits_addr),
        .io_mmio_req_bits_size(io_mmio_req_bits_size),
        .io_mmio_req_bits_cmd(io_mmio_req_bits_cmd),
        .io_mmio_req_bits_wmask(io_mmio_req_bits_wmask),
        .io_mmio_req_bits_wdata(io_mmio_req_bits_wdata),
        .io_mmio_resp_ready(io_mmio_resp_ready),
        .io_frontend_req_ready(io_frontend_req_ready),
        .io_frontend_resp_valid(io_frontend_resp_valid),
        .io_frontend_resp_bits_cmd(io_frontend_resp_bits_cmd),
        .io_frontend_resp_bits_rdata(io_frontend_resp_bits_rdata),
        .rvfi_valid(rvfi_valid), 
        .rvfi_order(rvfi_order), 
        .rvfi_insn(rvfi_insn), 
        .rvfi_trap(rvfi_trap), 
        .rvfi_halt(rvfi_halt), 
        .rvfi_intr(rvfi_intr), 
        .rvfi_mode(rvfi_mode), 
        .rvfi_ixl(rvfi_ixl), 
        .rvfi_rs1_addr(rvfi_rs1_addr), 
        .rvfi_rs2_addr(rvfi_rs2_addr), 
        .rvfi_rs1_rdata(rvfi_rs1_rdata), 
        .rvfi_rs2_rdata(rvfi_rs2_rdata), 
        .rvfi_rd_addr(rvfi_rd_addr), 
        .rvfi_rd_wdata(rvfi_rd_wdata), 
        .rvfi_pc_rdata(rvfi_pc_rdata), 
        .rvfi_pc_wdata(rvfi_pc_wdata), 
        .rvfi_mem_addr(rvfi_mem_addr), 
        .rvfi_mem_rmask(rvfi_mem_rmask), 
        .rvfi_mem_wmask(rvfi_mem_wmask), 
        .rvfi_mem_rdata(rvfi_mem_rdata), 
        .rvfi_mem_wdata(rvfi_mem_wdata) 
    );

endmodule